#!/bin/sh

# warn, but do not block commit for clippy warnings
cargo clippy || true

# warn and block commit for rustfmt formatting changes
cargo fmt --all -- --check
exit_status="$?"
if [ "$exit_status" -ne 0 ]; then
    >&2 echo "Review rustfmt changes"
    cargo fmt
fi

exit "$exit_status"
