sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
  - which cargo-clippy || cargo +"$(cat rustnightly.txt)" install clippy
script:
  - set -e
  - cargo build --verbose
  - cargo fmt -- --write-mode=diff
  - cargo +"$(cat rustnightly.txt)" clippy
  - cargo test --verbose
  - cargo test --release --verbose
  - set +e
