sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo install clippy
      fi
script:
  - set -e
  - cargo build --verbose
  - cargo fmt -- --write-mode=diff
  - (which cargo-clippy && cargo clippy) || exit 0
  - cargo test --verbose
  - cargo test --release --verbose
  - set +e
