sudo: false
language: rust
cache: cargo
os:
  - linux
  - windows
rust:
  - nightly
matrix:
  fast_finish: true
before_script:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt
script: ci/script.sh
