sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
script: ci/script.sh
