sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
script:
  - set -e
  - cargo build --verbose
  - cargo fmt --all -- --check # precondition: built grammar first
  - cargo clippy
  - cargo test --verbose
  - cargo test --release --verbose
  - set +e
