[package]
authors = ["Robert Gardner <rhg259@nyu.edu>"]
build = "build.rs"
description = "Command line shell"
name = "bsh-rs"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "bsh"

[build-dependencies]
lalrpop = "0.12.4"

[dependencies]
docopt = "0.6.75"
error-chain = "0.7.1"
lalrpop-util = "0.12.4"
nom = "1.0.1"
odds = "0.2.8"
rustc-serialize = "0.3.16"
wait-timeout = "0.1.3"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.rustyline]
git = "https://github.com/rgardner/rustyline"

[dev-dependencies]
rand = "0.3.15"

[features]
default = []
