[package]
authors = ["Robert Gardner <rhg259@nyu.edu>"]
description = "Command line shell"
name = "bsh-rs"
readme = "README.md"
version = "0.1.0"

[dependencies]
clippy = {version = "0.0.22", optional = true}

[features]
default = []
dev = ["clippy"]
