[package]
authors = ["Bob Gardner <bob.hn.gardner@gmail.com>"]
build = "build.rs"
description = "Command line shell"
edition = "2018"
license = "MIT or Apache-2.0"
name = "bsh"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "bsh"
path = "src/bin/bsh.rs"

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
dirs = "1.0.4"
docopt = "1.0.1"
failure = "0.1.2"
fern = "0.5.6"
lalrpop-util = "0.16.0"
libc = "0.2.43"
log = "0.4.5"
regex = "1.0.5"
rustyline = "2.1.0"
serde = "1.0.79"
serde_derive = "1.0.79"
atty = "0.2.11"
cfg-if = "0.1.5"

[dependencies.nix]
branch = "implement-libc-signal"
git = "https://github.com/rgardner/nix"

[dev-dependencies]
assert_cmd = "0.10.1"
chrono = "0.4.6"
escargot = "0.3.1"
lazy_static = "1.1.0"
predicates = "1.0.0"
tempfile = "3.0.4"
