[package]
authors = ["Robert Gardner <rhg259@nyu.edu>"]
description = "Command line shell"
name = "bsh-rs"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "bsh"

[dependencies]
docopt = "0.6.75"
error-chain = "0.7.1"
nom = "1.0.1"
odds = "0.2.8"
rustc-serialize = "0.3.16"
wait-timeout = "0.1"

[dependencies.clippy]
optional = true
version = "0.0.23"

[features]
default = []
dev = ["clippy"]
unstable = []
