[package]
authors = ["Robert Gardner <rhg259@nyu.edu>"]
description = "Command line shell"
name = "bsh-rs"
readme = "README.md"
version = "0.1.0"

[dependencies]
odds = "0.2.8"
quick-error = "0.1.4"
wait-timeout = "0.1"

[dependencies.clippy]
optional = true
version = "0.0.22"

[features]
default = []
dev = ["clippy"]
