[package]
authors = ["Robert Gardner <rhg259@nyu.edu>"]
build = "build.rs"
description = "Command line shell"
name = "bsh-rs"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "bsh"
path = "src/bin/bsh.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
docopt = "0.6.75"
env_logger = "0.4.3"
error-chain = "0.11.0"
lalrpop-util = "0.13.1"
log = "0.3.8"
odds = "0.2.8"
regex = "0.2.2"
rustc-serialize = "0.3.16"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.rustyline]
git = "https://github.com/rgardner/rustyline"

[dev-dependencies]
lazy_static = "0.2.9"
rand = "0.3.15"

[features]
default = []
