[package]
authors = ["Bob Gardner <bob.hn.gardner@gmail.com>"]
build = "build.rs"
description = "Command line shell"
license = "MIT or Apache-2.0"
name = "bsh"
readme = "README.md"
version = "0.1.0"

[[bin]]
name = "bsh"
path = "src/bin/bsh.rs"

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
dirs = "1.0.2"
docopt = "0.8.1"
failure = "0.1.1"
fern = "0.5.6"
lalrpop-util = "0.15.2"
log = "0.4.5"
regex = "0.2.2"
rustyline = "2.1.0"
serde = "1.0.18"
serde_derive = "1.0.18"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.nix]
branch = "implement-libc-signal"
git = "https://github.com/rgardner/nix"

[dev-dependencies]
assert_cli = "0.6.2"
chrono = "0.4.0"
lazy_static = "1.0.0"
tempfile = "3.0.4"

[features]
default = []
